meta:
  url:
  name: fusuma-verification
  author:
  thumbnail:
  description:
  sns:
    - twitter
slide:
  loop: true
  sidebar: true
  targetBlank: true
  showIndex: false
  isVertical: false
  code:
    languages:
      - javascript
      - cpp
extends:
  js: main.js
  css: style.css
