meta:
  url: https://issue-verifier.github.io/fusuma
  name: fusuma-verification
  author:
  description:
  sns:
    - twitter
slide:
  loop: false
  targetBlank: true
  code:
    languages:
      - javascript
      - cpp
extends:
  js: main.js
  css: style.css
