meta:
  url: https://issue-verifier.github.io/fusuma
  name: fusuma-verification
  author:
  thumbnail:
  description:
  sns:
    - twitter
slide:
  loop: false
  sidebar: true
  targetBlank: true
  showIndex: true
  isVertical: false
  code:
    languages:
      - javascript
      - cpp
extends:
  js: main.js
  css: style.css
build:
  useCache: false
  publicPath: /fusuma/
